### ISSUE TITLE
Save error when appending multiple times or modify just after appending

### ISSUE THREAD

**Issue by mpanighel** [Osndok/zim-plugin-append#7]
When I call the plugin multiple times (faster than autosaving) or I modify the page just after the plugin has been called, I get the Zim error dialog "SavePageErrorDialog" (Discard changes or save a copy) or even lose last edits.
This can be virtually avoided (or at least strongly limited) by reloading the page just before **and** after the appending, e.g. by adding at lines https://github.com/Osndok/zim-plugin-append/blob/7f18fc3ab602dfd5a3f0b342a8fc03604be9df72/append.py#L177 **and** https://github.com/Osndok/zim-plugin-append/blob/7f18fc3ab602dfd5a3f0b342a8fc03604be9df72/append.py#L285 the following:
```
if ui is not None:
    ui.reload_page()
```

**Comment by Osndok** [comment]
In my experience, these messages occur when zim notices that the file has changed on-disk during the save process, which (in my experience) happens when the plugin process "waits too long" for the busy zim master process (which might be busy appending to the page), and decides to remove the socket (!).

I really appreciate this report, but I'm not sure that your solution is technically correct.... I think that it would just start blending plugin calls between those with AND without a connection to the master process.

If you would, please try this minor tweak instead: https://github.com/Osndok/zim-desktop-wiki/commit/87d89df403dc7ff33845c6f16edae14c0efea814 ... I would be interested to know if it also works around the issue.

Even for just a tunable change, it is still (IMO) a bit hackish IMO... so if that solves your problem we should probably just open a ticket to the zim project (which I can fill in the details for) for better handling of... err... not deleting the control socket.

**Comment by mpanighel** [comment]
Thank for your reply!

> If you would, please try this minor tweak instead: Osndok/zim-desktop-wiki@87d89df ... I would be interested to know if it also works around the issue.

Unfortunately the tweak does not solve the issue. I tried with timeout up to `100`. As before, the outcome is the bug dialog reported below followed by the `Could not save page` dialog with `Invalid etag: None` message.

Bug dialog error:
```
This is zim 0.68-rc1
Platform: posix
Locale: en_US UTF-8
FS encoding: UTF-8
Python: (2, 7, 15, 'candidate', 1)
Gtk: (2, 24, 32)
Pygtk: (2, 24, 0)
No bzr version-info found

======= Traceback =======
  File "/usr/lib/python2.7/dist-packages/zim/actions.py", line 157, in do_activate
    self.__get__(instance, instance.__class__)()
  File "/usr/lib/python2.7/dist-packages/zim/actions.py", line 140, in func
    self.func(instance, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/zim/gui/__init__.py", line 1169, in reload_page
    self.notebook.flush_page_cache(self.page)
  File "/usr/lib/python2.7/dist-packages/zim/notebook/operations.py", line 365, in wrapper
    return method(notebook, *arg, **kwarg)
  File "/usr/lib/python2.7/dist-packages/zim/notebook/notebook.py", line 468, in flush_page_cache
    assert not page.modified, 'BUG: Flushing page with unsaved changes'
AssertionError: BUG: Flushing page with unsaved changes
```

The following is the output of `zim -D` when executing three consecutive appends without my workaround; the first one runs fine while the following two rise the `etag None` error (apparently it is not able to index the file):

```
DEBUG: Recieved remote call: ('/home/ssr', u'--plugin', u'append', u'--page=:Logbook:2018:09:26', u'--notebook=VT-STM', u'--literal=\r\n1 eV\r\n{{/LEED/2018/20180926/VT180926_A1_1eV_0.png?width=400}}\r\n[[file:////mnt/stm-nas/VTSTM/LEED/2018/20180926/VT180926_A1_1eV_0.png|VT180926_A1_1eV_0.png]]\r\n')
DEBUG: Loading config from: <zim.notebook.info.VirtualFile object at 0x7f39c23f80d0>
DEBUG: Loading config from: /mnt/stm-nas/VTSTM/Elogbooks/VT-STM/notebook.zim
DEBUG: Wrote /home/ssr/.config/zim/notebooks.list
NotebookInfo= <NotebookInfo: file:///mnt/stm-nas/VTSTM/Elogbooks/VT-STM>
Pagename= :Logbook:2018:09:26
Server= <zim.main.ZimApplication object at 0x7f39c66c7a90>
UI= <GtkInterface object at 0x7f39c5c5d690 (zim+gui+GtkInterface at 0x563a5cad6b80)>
Notebook?= <zim.notebook.notebook.Notebook object at 0x7f39c59ef310>
Page exists...
DEBUG: Store page: Logbook:2018:09:26
DEBUG: Index file: /mnt/stm-nas/VTSTM/Elogbooks/VT-STM/Logbook/2018/09/26.txt
DEBUG: Recieved remote call: ('/home/ssr', u'--plugin', u'append', u'--page=:Logbook:2018:09:26', u'--notebook=VT-STM', u'--literal=\r\n2 eV\r\n{{/LEED/2018/20180926/VT180926_A1_2eV_0.png?width=400}}\r\n[[file:////mnt/stm-nas/VTSTM/LEED/2018/20180926/VT180926_A1_2eV_0.png|VT180926_A1_2eV_0.png]]\r\n')
DEBUG: Loading config from: <zim.notebook.info.VirtualFile object at 0x7f39c23f8550>
DEBUG: Loading config from: /mnt/stm-nas/VTSTM/Elogbooks/VT-STM/notebook.zim
DEBUG: Wrote /home/ssr/.config/zim/notebooks.list
NotebookInfo= <NotebookInfo: file:///mnt/stm-nas/VTSTM/Elogbooks/VT-STM>
Pagename= :Logbook:2018:09:26
Server= <zim.main.ZimApplication object at 0x7f39c66c7a90>
UI= <GtkInterface object at 0x7f39c5c5d690 (zim+gui+GtkInterface at 0x563a5cad6b80)>
Notebook?= <zim.notebook.notebook.Notebook object at 0x7f39c59ef310>
Page exists...
INFO: Page changed on disk: Logbook:2018:09:26
DEBUG: Store page: Logbook:2018:09:26
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/zim/main/ipc.py", line 178, in callback
    handler(*args)
  File "/usr/lib/python2.7/dist-packages/zim/main/__init__.py", line 793, in _handle_incoming
    self.run(*args, pwd=pwd)
  File "/usr/lib/python2.7/dist-packages/zim/main/__init__.py", line 632, in run
    self._run_cmd(cmd, args) # test seam
  File "/usr/lib/python2.7/dist-packages/zim/main/__init__.py", line 643, in _run_cmd
    w = cmd.run()
  File "/home/ssr/.local/share/zim/plugins/append.py", line 239, in run
    ui.append_text_to_page(pagename, text);
  File "/usr/lib/python2.7/dist-packages/zim/gui/__init__.py", line 980, in append_text_to_page
    self.notebook.store_page(page)
  File "/usr/lib/python2.7/dist-packages/zim/notebook/operations.py", line 365, in wrapper
    return method(notebook, *arg, **kwarg)
  File "/usr/lib/python2.7/dist-packages/zim/notebook/notebook.py", line 487, in store_page
    page._store()
  File "/usr/lib/python2.7/dist-packages/zim/notebook/page.py", line 439, in _store
    self._store_tree(tree)
  File "/usr/lib/python2.7/dist-packages/zim/notebook/page.py", line 461, in _store_tree
    self._last_etag = self.source_file.writelines_with_etag(lines, self._last_etag)
  File "/usr/lib/python2.7/dist-packages/zim/newfs/base.py", line 727, in writelines_with_etag
    return self._write_with_etag(self.writelines, lines, etag)
  File "/usr/lib/python2.7/dist-packages/zim/newfs/base.py", line 738, in _write_with_etag
    if not self.verify_etag(etag):
  File "/usr/lib/python2.7/dist-packages/zim/newfs/base.py", line 754, in verify_etag
    raise AssertionError('Invalid etag: %r' % etag)
AssertionError: Invalid etag: None
DEBUG: Recieved remote call: ('/home/ssr', u'--plugin', u'append', u'--page=:Logbook:2018:09:26', u'--notebook=VT-STM', u'--literal=\r\n3 eV\r\n{{/LEED/2018/20180926/VT180926_A1_3eV_0.png?width=400}}\r\n[[file:////mnt/stm-nas/VTSTM/LEED/2018/20180926/VT180926_A1_3eV_0.png|VT180926_A1_3eV_0.png]]\r\n')
DEBUG: Loading config from: <zim.notebook.info.VirtualFile object at 0x7f39c23f8c90>
DEBUG: Loading config from: /mnt/stm-nas/VTSTM/Elogbooks/VT-STM/notebook.zim
DEBUG: Wrote /home/ssr/.config/zim/notebooks.list
NotebookInfo= <NotebookInfo: file:///mnt/stm-nas/VTSTM/Elogbooks/VT-STM>
Pagename= :Logbook:2018:09:26
Server= <zim.main.ZimApplication object at 0x7f39c66c7a90>
UI= <GtkInterface object at 0x7f39c5c5d690 (zim+gui+GtkInterface at 0x563a5cad6b80)>
Notebook?= <zim.notebook.notebook.Notebook object at 0x7f39c59ef310>
Page exists...
DEBUG: Store page: Logbook:2018:09:26
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/zim/main/ipc.py", line 178, in callback
    handler(*args)
  File "/usr/lib/python2.7/dist-packages/zim/main/__init__.py", line 793, in _handle_incoming
    self.run(*args, pwd=pwd)
  File "/usr/lib/python2.7/dist-packages/zim/main/__init__.py", line 632, in run
    self._run_cmd(cmd, args) # test seam
  File "/usr/lib/python2.7/dist-packages/zim/main/__init__.py", line 643, in _run_cmd
    w = cmd.run()
  File "/home/ssr/.local/share/zim/plugins/append.py", line 239, in run
    ui.append_text_to_page(pagename, text);
  File "/usr/lib/python2.7/dist-packages/zim/gui/__init__.py", line 980, in append_text_to_page
    self.notebook.store_page(page)
  File "/usr/lib/python2.7/dist-packages/zim/notebook/operations.py", line 365, in wrapper
    return method(notebook, *arg, **kwarg)
  File "/usr/lib/python2.7/dist-packages/zim/notebook/notebook.py", line 487, in store_page
    page._store()
  File "/usr/lib/python2.7/dist-packages/zim/notebook/page.py", line 439, in _store
    self._store_tree(tree)
  File "/usr/lib/python2.7/dist-packages/zim/notebook/page.py", line 461, in _store_tree
    self._last_etag = self.source_file.writelines_with_etag(lines, self._last_etag)
  File "/usr/lib/python2.7/dist-packages/zim/newfs/base.py", line 727, in writelines_with_etag
    return self._write_with_etag(self.writelines, lines, etag)
  File "/usr/lib/python2.7/dist-packages/zim/newfs/base.py", line 738, in _write_with_etag
    if not self.verify_etag(etag):
  File "/usr/lib/python2.7/dist-packages/zim/newfs/base.py", line 754, in verify_etag
    raise AssertionError('Invalid etag: %r' % etag)
AssertionError: Invalid etag: None
DEBUG: Store page in background: Logbook:2018:09:26
ERROR: Error in background save
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/zim/notebook/notebook.py", line 516, in _store_page_async_thread_main
    page._store_tree(parsetree)
  File "/usr/lib/python2.7/dist-packages/zim/notebook/page.py", line 461, in _store_tree
    self._last_etag = self.source_file.writelines_with_etag(lines, self._last_etag)
  File "/usr/lib/python2.7/dist-packages/zim/newfs/base.py", line 727, in writelines_with_etag
    return self._write_with_etag(self.writelines, lines, etag)
  File "/usr/lib/python2.7/dist-packages/zim/newfs/base.py", line 738, in _write_with_etag
    if not self.verify_etag(etag):
  File "/usr/lib/python2.7/dist-packages/zim/newfs/base.py", line 754, in verify_etag
    raise AssertionError('Invalid etag: %r' % etag)
AssertionError: Invalid etag: None
```

With my workaround, the output of all following appends is correct like the first one above and between each one appears this reload_page output:

```
INFO: Open page: Logbook:2018:09:26 (Logbook:2018:09:26)
DEBUG: Already selected: "Logbook:2018:09:26"
DEBUG: BackgroundCheck started
DEBUG: BackgroundCheck found out-of-date
DEBUG: Index folder: /mnt/stm-nas/VTSTM/Elogbooks/VT-STM/Logbook/2018/09
DEBUG: Index file: /mnt/stm-nas/VTSTM/Elogbooks/VT-STM/Logbook/2018/09/26.txt
DEBUG: BackgroundCheck started
DEBUG: BackgroundCheck finished
```

**Comment by Osndok** [comment]
I **was** able to replicate this on the **stock zim v0.68** both **with and without** your suggested modification. Although, reloading the page **did** seem to bring it down to about 20% of the stock incidence!

Most interesting of all, when running the following script a few times, I was able to easily and reliably **bring my testing VM to a grinding halt**:

```
#!/bin/bash
# !!!!! DANGER !!!! MAY KILL YOUR SYSTEM!!!!
for N in $(seq 1 100)
do
    zim --plugin append --page Zim:Test --literal testing$N &
done
```

However, I found that this problem does not seem to be present with the latest development version of zim. I suspect that it has been fixed by the page-loading performance optimizations recently put in place as a result of https://github.com/jaap-karssenberg/zim-desktop-wiki/issues/519 ... but don't really have the time to chase it down any further.

Anyway... absent more solid info & understanding, this is going to be a WONTFIX b/c my humble plugin cannot hope to compensate for deep and soon-to-be-obsolete problems with zim. I hope your fix is adequate for your use case, but if you continue to get the messages, you might try updating to zim's git HEAD, or v0.69 when it comes out.

**Comment by mpanighel** [comment]
@Osndok The issue is still occurring also with the latest Zim from master. Anyway my fix is working for my case. Thank you.
